installation script finished and INSTALL doc updated
Quite some changes... a big commit

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,4 +12,58 @@ install usr/local/etc/ipUpdaterd.conf /usr/local/etc
 install usr/local/sbin/ipUpdaterd /usr/local/sbin
 cat /dev/null > /var/log/ipUpdaterd.log && chcon -u system_u /var/log/ipUpdaterd.log && restorecon /var/log/ipUpdaterd.log
 
-exit 0
+# configure
+echo -n "What's your login? "
+read 'login'
+
+echo -n "What's your password? "
+read -s 'password'
+password=$(echo -n $password | base64)
+
+echo -ne "\nWhat hostname to use? (example: myhost.mydomain.com) "
+read 'host'
+
+echo -n "Do you want me to get your IP from an interface? (example: no | eth0, wlan0, ppp0, etc) "
+read 'interface'
+
+if [ $(echo -n $interface | grep -i 'no') ]; then
+    ip="myip=''"
+else
+    ip="myip='$(ip -4 address show ${interface} |/bin/awk -F'[/ ]' '/inet/{print$6}')'"
+fi
+
+echo -n " \
+
+Is this correct?
+
+Login:      ${login}
+Password:   <hidden>
+Host:       ${host}
+interface:  ${interface}
+
+answer (yes|no) " 
+read 'answer'
+
+if [ $(echo -n $answer | grep -i 'yes') ]; then
+    sed -ri "s@login='<some user>'@login=${login}@g" /usr/local/etc/ipUpdaterd.conf
+    sed -ri "s@password='<some cool password base64 encoded>'@password='${password}'@g" /usr/local/etc/ipUpdaterd.conf
+    sed -ri "s@host='<some, already registered, host>'@host='${host}'@g" /usr/local/etc/ipUpdaterd.conf
+    sed -ri "s@myip=''@${ip}@g" /usr/local/etc/ipUpdaterd.conf
+    
+    cat <<EOF
+
+        Your configuration is done. Feel free to start the service by typing:
+            su -c 'service ipUpdaterd start'
+        
+        And, if you want this service to start at boot, activate it:
+            su -c 'chkconfig ipUpdaterd on'
+    
+        Thank you for using it!
+
+EOF
+
+    exit 0
+else
+    echo "Configuration aborted. Please, reinstall by re-running this script"
+    exit 2
+fi
